from __future__ import annotations

from pipeline.models import SourceDefinition, SourceType

SEED_SOURCES: list[SourceDefinition] = [
    SourceDefinition(
        source_id="src_reuters_top",
        name="Reuters Top News",
        source_type=SourceType.rss,
        category="global",
        homepage_url="https://www.reuters.com/",
        feed_url="https://feeds.reuters.com/reuters/topNews",
        country="global",
        priority=95,
        reliability_score=0.92,
    ),
    SourceDefinition(
        source_id="src_ap_top",
        name="Associated Press",
        source_type=SourceType.rss,
        category="global",
        homepage_url="https://apnews.com/",
        feed_url="https://apnews.com/hub/ap-top-news?output=1",
        country="us",
        priority=93,
        reliability_score=0.92,
    ),
    SourceDefinition(
        source_id="src_bbc_world",
        name="BBC World",
        source_type=SourceType.rss,
        category="global",
        homepage_url="https://www.bbc.com/news/world",
        feed_url="https://feeds.bbci.co.uk/news/world/rss.xml",
        country="gb",
        priority=88,
        reliability_score=0.88,
    ),
    SourceDefinition(
        source_id="src_the_hindu",
        name="The Hindu",
        source_type=SourceType.rss,
        category="india",
        homepage_url="https://www.thehindu.com/",
        feed_url="https://www.thehindu.com/news/national/feeder/default.rss",
        country="in",
        priority=82,
        reliability_score=0.82,
    ),
    SourceDefinition(
        source_id="src_indian_express",
        name="Indian Express",
        source_type=SourceType.rss,
        category="india",
        homepage_url="https://indianexpress.com/",
        feed_url="https://indianexpress.com/section/india/feed/",
        country="in",
        priority=80,
        reliability_score=0.8,
    ),
    SourceDefinition(
        source_id="src_hacker_news",
        name="Hacker News",
        source_type=SourceType.rss,
        category="technology",
        homepage_url="https://news.ycombinator.com/",
        feed_url="https://hnrss.org/frontpage",
        country="global",
        priority=72,
        reliability_score=0.68,
    ),
    SourceDefinition(
        source_id="src_the_verge",
        name="The Verge",
        source_type=SourceType.rss,
        category="technology",
        homepage_url="https://www.theverge.com/",
        feed_url="https://www.theverge.com/rss/index.xml",
        country="us",
        priority=74,
        reliability_score=0.74,
    ),
    SourceDefinition(
        source_id="src_mit_ai",
        name="MIT News AI",
        source_type=SourceType.rss,
        category="artificial_intelligence",
        homepage_url="https://news.mit.edu/topic/artificial-intelligence2",
        feed_url="https://news.mit.edu/rss/topic/artificial-intelligence2",
        country="us",
        priority=78,
        reliability_score=0.86,
    ),
    SourceDefinition(
        source_id="src_google_ai",
        name="Google AI Blog",
        source_type=SourceType.rss,
        category="artificial_intelligence",
        homepage_url="https://blog.google/technology/ai/",
        feed_url="https://blog.google/technology/ai/rss/",
        country="us",
        priority=65,
        reliability_score=0.74,
    ),
    SourceDefinition(
        source_id="src_ft_world",
        name="Financial Times World",
        source_type=SourceType.rss,
        category="business",
        homepage_url="https://www.ft.com/",
        feed_url="https://www.ft.com/world?format=rss",
        country="gb",
        priority=80,
        reliability_score=0.86,
    ),
    SourceDefinition(
        source_id="src_economist",
        name="The Economist",
        source_type=SourceType.rss,
        category="economy",
        homepage_url="https://www.economist.com/",
        feed_url="https://www.economist.com/latest/rss.xml",
        country="gb",
        priority=78,
        reliability_score=0.84,
    ),
    SourceDefinition(
        source_id="src_carbonbrief",
        name="Carbon Brief",
        source_type=SourceType.rss,
        category="climate",
        homepage_url="https://www.carbonbrief.org/",
        feed_url="https://www.carbonbrief.org/feed/",
        country="gb",
        priority=77,
        reliability_score=0.84,
    ),
    SourceDefinition(
        source_id="src_iea",
        name="International Energy Agency",
        source_type=SourceType.rss,
        category="energy",
        homepage_url="https://www.iea.org/",
        feed_url="https://www.iea.org/rss/news.xml",
        country="global",
        priority=82,
        reliability_score=0.9,
    ),
    SourceDefinition(
        source_id="src_foreign_affairs",
        name="Foreign Affairs",
        source_type=SourceType.rss,
        category="geopolitics",
        homepage_url="https://www.foreignaffairs.com/",
        feed_url="https://www.foreignaffairs.com/rss.xml",
        country="us",
        priority=76,
        reliability_score=0.82,
    ),
    SourceDefinition(
        source_id="src_nature_news",
        name="Nature News",
        source_type=SourceType.rss,
        category="science",
        homepage_url="https://www.nature.com/news",
        feed_url="https://www.nature.com/nature.rss",
        country="global",
        priority=78,
        reliability_score=0.86,
    ),
    SourceDefinition(
        source_id="src_wired",
        name="WIRED",
        source_type=SourceType.rss,
        category="internet_culture",
        homepage_url="https://www.wired.com/",
        feed_url="https://www.wired.com/feed/rss",
        country="us",
        priority=70,
        reliability_score=0.72,
    ),
]


def seed_sources(repository) -> int:
    existing = {source.source_id for source in repository.list_sources()}
    count = 0
    for source in SEED_SOURCES:
        if source.source_id not in existing:
            repository.upsert_source(source)
            count += 1
    return count
