from __future__ import annotations

import html
from pathlib import Path
from typing import Any

from ..downloader import project_relative
from ..models import AssetType, ProviderReport, StorySegment, VisualAsset, VisualProvider, VisualQuery
from ..query_builder import compact_text, tokenize


class ScreenshotProvider(VisualProvider):
    name = "screenshot_provider"

    def __init__(self, project_root: Path) -> None:
        self.project_root = project_root

    def search(
        self,
        *,
        manifest: dict[str, Any],
        story_json_path: Path,
        segments: list[StorySegment],
        queries: list[VisualQuery],
    ) -> tuple[list[VisualAsset], ProviderReport]:
        report = ProviderReport(provider=self.name, query_count=len(queries))
        raw = manifest.get("raw") if isinstance(manifest.get("raw"), dict) else {}
        story_id = str(manifest.get("story_id", story_json_path.parent.name))
        output_dir = story_json_path.parent / "visuals" / "generated"
        output_dir.mkdir(parents=True, exist_ok=True)
        assets: list[VisualAsset] = []
        for segment in segments:
            path = output_dir / f"{segment.segment_id}_source_context.svg"
            self._write_context_svg(path, manifest=manifest, segment=segment)
            relative = project_relative(path, self.project_root)
            asset_type = self._asset_type_for_segment(segment)
            assets.append(
                VisualAsset(
                    asset_id=f"generated_{story_id}_{segment.segment_id}",
                    asset_type=asset_type,
                    title=f"{segment.title} context graphic",
                    provider=self.name,
                    path=relative,
                    source_url=raw.get("source_url"),
                    source_name=raw.get("source_name") or "SynthPost",
                    license="Generated by SynthPost",
                    usage_note="Story-specific editorial graphic generated from manifest text; not scraped third-party media.",
                    attribution=f"Source: {raw.get('source_name', 'SynthPost')}",
                    downloaded_path=relative,
                    story_id=story_id,
                    segment_id=segment.segment_id,
                    keywords=segment.keywords,
                    safe_to_use=True,
                    fallback_reason=f"generated_{asset_type.value}_fallback",
                    width=1600,
                    height=900,
                    extra={"visual_role": asset_type.value if asset_type != AssetType.GENERATED else "context_graphic"},
                )
            )
        report.candidate_count = len(assets)
        return assets, report

    def _write_context_svg(self, path: Path, *, manifest: dict[str, Any], segment: StorySegment) -> None:
        raw = manifest.get("raw") if isinstance(manifest.get("raw"), dict) else {}
        script = manifest.get("script") if isinstance(manifest.get("script"), dict) else {}
        source_name = compact_text(raw.get("source_name") or "SynthPost")
        category = compact_text(script.get("category") or raw.get("category") or "News").upper()
        title_lines = self._wrap(segment.title.upper(), 36, 3)
        fact_source = segment.text.replace(segment.title, "", 1).strip()
        fact_lines = self._wrap(fact_source or raw.get("summary") or "", 58, 4)
        keywords = [item.upper() for item in segment.keywords[:5]]
        keyword_nodes = []
        x = 120
        for keyword in keywords:
            label = html.escape(keyword[:24])
            width = max(120, min(310, len(label) * 13 + 34))
            keyword_nodes.append(
                f'<rect x="{x}" y="642" width="{width}" height="52" rx="0" fill="#071B33" stroke="#1F7BFF" stroke-width="2"/>'
                f'<text x="{x + 17}" y="676" font-size="22" fill="#F5F7FA" font-family="Inter, Arial, sans-serif">{label}</text>'
            )
            x += width + 18
            if x > 1400:
                break

        title_svg = "\n".join(
            f'<text x="120" y="{245 + index * 78}" font-size="64" fill="#F5F7FA" font-family="Georgia, serif" font-weight="700">{html.escape(line)}</text>'
            for index, line in enumerate(title_lines)
        )
        fact_svg = "\n".join(
            f'<text x="122" y="{520 + index * 42}" font-size="30" fill="#AAB4C2" font-family="Inter, Arial, sans-serif">{html.escape(line)}</text>'
            for index, line in enumerate(fact_lines)
        )
        svg = f"""<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900">
  <defs>
    <linearGradient id="bg" x1="0" x2="1" y1="0" y2="1">
      <stop offset="0" stop-color="#050A14"/>
      <stop offset="0.55" stop-color="#071B33"/>
      <stop offset="1" stop-color="#050A14"/>
    </linearGradient>
    <pattern id="grid" width="80" height="80" patternUnits="userSpaceOnUse">
      <path d="M 80 0 L 0 0 0 80" fill="none" stroke="#5C7FA6" stroke-opacity="0.16" stroke-width="1"/>
    </pattern>
  </defs>
  <rect width="1600" height="900" fill="url(#bg)"/>
  <rect width="1600" height="900" fill="url(#grid)" opacity="0.85"/>
  <rect x="76" y="74" width="1448" height="752" fill="#050A14" fill-opacity="0.42" stroke="#5C7FA6" stroke-opacity="0.7" stroke-width="2"/>
  <text x="120" y="144" font-size="32" fill="#FFD84A" font-family="Inter, Arial, sans-serif" font-weight="800">{html.escape(category)}</text>
  <text x="120" y="184" font-size="24" fill="#AAB4C2" font-family="Inter, Arial, sans-serif">{html.escape(source_name.upper())}</text>
  <text x="1160" y="144" font-size="24" fill="#F5F7FA" fill-opacity="0.62" font-family="Inter, Arial, sans-serif" font-weight="700">SYNTHPOST CONTEXT</text>
  <line x1="120" y1="203" x2="540" y2="203" stroke="#1F7BFF" stroke-width="4"/>
  {title_svg}
  <line x1="120" y1="462" x2="980" y2="462" stroke="#5C7FA6" stroke-opacity="0.55" stroke-width="2"/>
  {fact_svg}
  {''.join(keyword_nodes)}
</svg>
"""
        path.write_text(svg, encoding="utf-8")

    def _wrap(self, value: object, width: int, max_lines: int) -> list[str]:
        words = compact_text(value).split()
        lines: list[str] = []
        current: list[str] = []
        for word in words:
            candidate = " ".join([*current, word])
            if len(candidate) > width and current:
                lines.append(" ".join(current))
                current = [word]
            else:
                current.append(word)
            if len(lines) >= max_lines:
                break
        if current and len(lines) < max_lines:
            lines.append(" ".join(current))
        if not lines:
            return ["SYNTHPOST CONTEXT"]
        if len(lines) == max_lines and len(" ".join(words)) > sum(len(line) for line in lines):
            lines[-1] = lines[-1].rstrip(" .") + "..."
        return lines

    def _asset_type_for_segment(self, segment: StorySegment) -> AssetType:
        haystack = f"{segment.title} {segment.text} {' '.join(segment.keywords)}".lower()
        tokens = set(tokenize(haystack))
        if tokens & {"map", "border", "route", "region", "location"}:
            return AssetType.MAP
        if tokens & {"chart", "graph", "markets", "price", "inflation", "rate"}:
            return AssetType.CHART
        if tokens & {"document", "order", "filing", "statement", "tariff", "report"}:
            return AssetType.DOCUMENT
        if tokens & {"screenshot", "app", "platform", "website", "source"}:
            return AssetType.SCREENSHOT
        return AssetType.GENERATED
