export type TemplateDefinition = {
  template_id: string;
  name: string;
  description: string;
  component: string;
  supported_media_types: string[];
  supported_content_roles: string[];
  anchor_visible: boolean | null;
  anchor_speaking: boolean | null;
  visual_audio_policy: 'muted' | 'source_or_muted' | 'narration_only' | 'mixed_explicit';
  required_fields: string[];
  default_duration: number;
  compatible_aspect_ratios: string[];
  fallback_template_id: string;
  editor_preview_icon: string;
  validation_rules: string[];
};

export const templateRegistry: Record<string, TemplateDefinition> = {
  split_anchor_visual: {
    template_id: 'split_anchor_visual',
    name: 'Split Anchor + Visual',
    description: 'Anchor narrates while supporting media is displayed.',
    component: 'TimelineStory.SplitAnchorVisual',
    supported_media_types: ['image', 'video', 'document', 'chart', 'map', 'fallback'],
    supported_content_roles: ['evidence', 'primary_footage', 'context', 'explanation', 'location', 'person', 'document', 'data', 'atmosphere', 'fallback'],
    anchor_visible: true,
    anchor_speaking: true,
    visual_audio_policy: 'muted',
    required_fields: ['script_text'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'split',
    validation_rules: ['supporting_video_muted_by_default', 'attribution_visible_when_required'],
  },
  fullscreen_news_visual: {
    template_id: 'fullscreen_news_visual',
    name: 'Full-Screen News Visual',
    description: 'Primary source clip or important news visual fills the frame.',
    component: 'TimelineStory.FullscreenNewsVisual',
    supported_media_types: ['image', 'video'],
    supported_content_roles: ['primary_footage', 'evidence', 'context', 'atmosphere'],
    anchor_visible: false,
    anchor_speaking: false,
    visual_audio_policy: 'source_or_muted',
    required_fields: ['visual.path', 'overlays.attribution'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'split_anchor_visual',
    editor_preview_icon: 'video',
    validation_rules: ['source_audio_explicit', 'attribution_required'],
  },
  fullscreen_anchor: {
    template_id: 'fullscreen_anchor',
    name: 'Full-Screen Anchor',
    description: 'Opening, closing, or direct address.',
    component: 'TimelineStory.FullscreenAnchor',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['fallback', 'context'],
    anchor_visible: true,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['script_text'],
    default_duration: 7,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_anchor',
    editor_preview_icon: 'anchor',
    validation_rules: [],
  },
  fallback_anchor: {
    template_id: 'fallback_anchor',
    name: 'Fallback Anchor',
    description: 'Safe anchor-only fallback.',
    component: 'TimelineStory.FullscreenAnchor',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['fallback', 'context'],
    anchor_visible: true,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['script_text'],
    default_duration: 7,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'anchor',
    validation_rules: [],
  },
  quote_card: {
    template_id: 'quote_card',
    name: 'Quote Card',
    description: 'Large quote with source.',
    component: 'TimelineStory.QuoteCard',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['evidence', 'context'],
    anchor_visible: null,
    anchor_speaking: null,
    visual_audio_policy: 'muted',
    required_fields: ['overlays.quote_text', 'overlays.attribution'],
    default_duration: 7,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'quote',
    validation_rules: ['quote_requires_claim'],
  },
  document_callout: {
    template_id: 'document_callout',
    name: 'Document Callout',
    description: 'Document or report excerpt with source.',
    component: 'TimelineStory.DocumentCallout',
    supported_media_types: ['document', 'image', 'fallback'],
    supported_content_roles: ['document', 'evidence'],
    anchor_visible: true,
    anchor_speaking: true,
    visual_audio_policy: 'muted',
    required_fields: ['visual.path', 'overlays.document_source'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'document',
    validation_rules: ['document_source_required'],
  },
  chart_explainer: {
    template_id: 'chart_explainer',
    name: 'Chart Explainer',
    description: 'Structured editorial chart.',
    component: 'TimelineStory.ChartExplainer',
    supported_media_types: ['chart', 'fallback', 'image'],
    supported_content_roles: ['data', 'explanation'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['overlays.data'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'chart',
    validation_rules: [],
  },
  map_explainer: {
    template_id: 'map_explainer',
    name: 'Map Explainer',
    description: 'Structured map/location explainer.',
    component: 'TimelineStory.MapExplainer',
    supported_media_types: ['map', 'fallback', 'image'],
    supported_content_roles: ['location', 'explanation'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['overlays.data'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'map',
    validation_rules: [],
  },
  timeline_explainer: {
    template_id: 'timeline_explainer',
    name: 'Timeline Explainer',
    description: 'Chronological event card.',
    component: 'TimelineStory.TimelineExplainer',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['explanation', 'context'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['overlays.data'],
    default_duration: 9,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'timeline',
    validation_rules: [],
  },
  comparison_card: {
    template_id: 'comparison_card',
    name: 'Comparison Card',
    description: 'Two-column comparison.',
    component: 'TimelineStory.ComparisonCard',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['explanation', 'data', 'context'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['overlays.data'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'compare',
    validation_rules: [],
  },
  bullet_summary: {
    template_id: 'bullet_summary',
    name: 'Bullet Summary',
    description: 'Branded summary card.',
    component: 'TimelineStory.BulletSummary',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['explanation', 'context', 'fallback'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['overlays.data'],
    default_duration: 7,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fallback_context_card',
    editor_preview_icon: 'bullets',
    validation_rules: [],
  },
  source_screenshot: {
    template_id: 'source_screenshot',
    name: 'Source Screenshot',
    description: 'Source screenshot with attribution.',
    component: 'TimelineStory.SourceScreenshot',
    supported_media_types: ['image', 'document'],
    supported_content_roles: ['document', 'evidence'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'muted',
    required_fields: ['visual.path', 'overlays.attribution'],
    default_duration: 8,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'document_callout',
    editor_preview_icon: 'screenshot',
    validation_rules: ['attribution_required'],
  },
  fallback_context_card: {
    template_id: 'fallback_context_card',
    name: 'Fallback Context Card',
    description: 'Branded fallback editorial graphic.',
    component: 'TimelineStory.FallbackContextCard',
    supported_media_types: ['fallback', 'image'],
    supported_content_roles: ['fallback', 'context', 'explanation'],
    anchor_visible: false,
    anchor_speaking: true,
    visual_audio_policy: 'narration_only',
    required_fields: ['script_text'],
    default_duration: 7,
    compatible_aspect_ratios: ['16:9'],
    fallback_template_id: 'fullscreen_anchor',
    editor_preview_icon: 'context',
    validation_rules: [],
  },
};

export const getTemplateDefinition = (templateId: string): TemplateDefinition => templateRegistry[templateId] ?? templateRegistry.fallback_context_card;
export const templateIds = Object.keys(templateRegistry);
